### ISSUE TITLE
add new functions

### ISSUE THREAD

**Issue by maravento** [dev-jan/wifi-qrcode-generator#1]
You could add new functions, such as:
Proxy IP:
Proxy port:
Automatic configuration proxy: URL Pac
IP settings:
Static: IP, Gateway, netmask, DNS1, DNS2

thanks in advanced

**Comment by dev-jan** [comment]
Hello @maravento 

Thank you for your request!

According to the specifications about the Wifi QR-Code, it's not possible to pass proxy informations and other configurations like Gateway, DNS-Server, etc. with the QR code. The Google ZXing project describes the possible values here: https://github.com/zxing/zxing/wiki/Barcode-Contents

So I cannot do much here, as the readers do not support this feature (yet)
